config/routes.rb
TwitterRails::Application.routes.draw do
  get "session/create"
  get "home/index"

  root 'home#index'
  match 'auth/twitter/callback' => 'session#create', via: [:get, :post]
  match 'signout' , to: 'session#destroy', as: 'signout', via: [:get, :post]
  match 'client/create' => 'client#create' , via:[:post]

end

app/models/tweet.rb
class Tweet

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :tweet_content
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  # def self.from_omniauth(auth)
  #    where(uid: auth[:uid]).first || create_from_omniauth(auth)
  # end
  #
  # def self.create_from_omniauth(auth)
  #   create do |user|
  #     user.provider = auth['provider']
  #     user.uid = auth['uid']
  #     user.name = auth['info']['nickname']
  #   end
  # end

  def self.find_or_create_from_auth_hash(auth_hash)
    user = where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create
    user.update(
        name: auth_hash.info.nickname,
        profile_image: auth_hash.info.image,
        token: auth_hash.credentials.token,
        secret: auth_hash.credentials.secret
    )
    user
  end

  def twitter
    client ||= Twitter::REST::Client.new do |config|
      config.consumer_key        =  Rails.application.secrets.twitter_api_key
      config.consumer_secret     =  Rails.application.secrets.twitter_api_secret
      config.access_token        =  token
      config.access_token_secret =  secret
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/client_controller.rb
class ClientController < ApplicationController
  def create
    current_user.twitter.update(params[:tweet][:tweet_content])
    redirect_to root_url, :notice => 'Tweet successfully posted'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    user =  User.find_or_create_from_auth_hash(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/client/create.html.erb
<%= form_for (@tweet = Tweet.new, :url => client_create_url) do |tweet_form| %>
    <%= tweet_form.text_area :tweet_content, :id => "tweet" %>
    <%= tweet_form.submit "Tweet" %>
<% end %>

app/views/home/index.html.erb
<%= form_for(@tweet = Tweet.new, :url => client_create_path) do |tweet_form| %>
    <div class="form-group">
      <%= tweet_form.text_area :tweet_content, :id => "tweet", class: "form-control", placeholder: "Enter Your tweet text here" %>
    </div>
    <div class="form-group">
      <%= tweet_form.submit "Post message to twitter" , class: "btn btn-lg btn-success"  %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterRails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

#todo handle the case of denial from twitter
<div class="container">
  <div class="header">
    <ul class="nav nav-pills pull-right">
      <% if current_user %>
          <li ><%= link_to "Sign out", signout_path%>  </li>
      <%end %>
    </ul>
    <h3 class="text-muted">Twitter Client</h3>
  </div>

  <h3 class="text-muted"></h3>

  <% if flash[:error] -%>
      <p class='error'><%=h flash[:error] %></p>
  <% end -%>
  <% if flash[:notice] -%>
      <p class='notice'><%=h flash[:notice] %></p>
  <% end -%>

  <div class="jumbotron">
    <% if current_user %>
          <%= yield %>
    <% else %>
        <p><%= link_to "Sign in with Twitter", "/auth/twitter" %></p>
    <% end %>

  </div>

  <div class="footer">
    <p>© Company 2014</p>
  </div>

</div>

</body>
</html>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>